platform :ios, '13.0'

use_frameworks!
use_modular_headers!

target 'Runner' do
  # We are skipping the 'load' line entirely to avoid the crash
  # Flutter's Mac server will still find the pods via the pubspec.yaml
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      # This line helps fix common build errors on cloud Macs
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end